// VBConversions Note: VB project level imports
// End of VB project level imports


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace interApps.DNN.Modules.IdentitySwitcher
{

    public partial class Settings
	{
		
		///<summary>
		///tblDesignTable control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.HtmlControls.HtmlTable tblDesignTable;
		
		///<summary>
		///trHostSettings control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.HtmlControls.HtmlTableRow trHostSettings;
		
		///<summary>
		///plIncludeHostUser control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.UserControl plIncludeHostUser;
		
		///<summary>
		///cbIncludeHostUser control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.CheckBox cbIncludeHostUser;
		
		///<summary>
		///plUseAjax control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.UserControl plUseAjax;
		
		///<summary>
		///cbUseAjax control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.CheckBox cbUseAjax;
		
		///<summary>
		///plSortBy control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.UserControl plSortBy;
		
		///<summary>
		///rbSortBy control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList rbSortBy;
	}
}

