// VBConversions Note: VB project level imports
using System.Web.UI.WebControls;
using DotNetNuke.Services.Exceptions;
using DotNetNuke.Common.Utilities;
using DotNetNuke.Entities.Tabs;
using System.Text.RegularExpressions;
using System;
using DotNetNuke.Entities;
using DotNetNuke.Framework;
using DotNetNuke;
using System.Text;
using System.Web.UI.HtmlControls;
using DotNetNuke.Services;
using DotNetNuke.Common;
using DotNetNuke.UI;
using DotNetNuke.Data;
using System.Collections;
using System.Web.Profile;
using System.Collections.Specialized;
using Microsoft.VisualBasic;
using System.Diagnostics;
using DotNetNuke.Security;
using System.Web.UI;
using System.Web.SessionState;
using System.Data;
using System.Configuration;
using System.Web;
using DotNetNuke.Services.Localization;
using System.Web.Security;
using DotNetNuke.Modules;
using System.Web.Caching;
using System.Web.UI.WebControls.WebParts;
using System.Collections.Generic;
// End of VB project level imports


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace interApps.DNN.Modules.IdentitySwitcher
{
	
	public partial class ViewIdentitySwitcher
	{
		
		///<summary>
		///UpdatePanel1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.UpdatePanel UpdatePanel1;
		
		///<summary>
		///lblSearch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.Label lblSearch;
		
		///<summary>
		///txtSearch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.TextBox txtSearch;
		
		///<summary>
		///ddlSearchType control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList ddlSearchType;
		
		///<summary>
		///cmdSearch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::DotNetNuke.UI.WebControls.CommandButton cmdSearch;
		
		///<summary>
		///lblSwitchToIdentity control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.Label lblSwitchToIdentity;
		
		///<summary>
		///cboUsers control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.DropDownList cboUsers;
		
		///<summary>
		///cmdSwitch control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::DotNetNuke.UI.WebControls.CommandButton cmdSwitch;
		
		///<summary>
		///UpdateProgress1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.UpdateProgress UpdateProgress1;
	}
}

